services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn myportfolio.wsgi:application"
    envVars:
      - key: postgresql://aa_qd20_user:2OfwITtcQbfeVoO6ydEWeQ9QRW07uI1x@dpg-cqbogg8gph6c73c3uftg-a.oregon-postgres.render.com/aa_qd20
        fromDatabase:
          name: aa_qd20
          property: connectionString
